// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAPI;

namespace TravelAPI.Migrations
{
    [DbContext(typeof(TravelAPIContext))]
    [Migration("20200522115853_Add_More_Data")]
    partial class Add_More_Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TravelAPI.Models.AttractionModel", b =>
                {
                    b.Property<int>("AttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsChildFriendly")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("AttractionId");

                    b.HasIndex("CityId");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            AttractionId = 1,
                            CityId = 1,
                            Information = "The empty niches of the Buddha statues dominate the Bamiyan valley. Carved in the 6th century, the two statues, standing 38m and 55m respectively, were the tallest standing statues of Buddha ever made.",
                            IsChildFriendly = true,
                            Location = "Bamiyan Valley, west of Kabul",
                            Name = "Buddha Niches",
                            Rating = 4
                        },
                        new
                        {
                            AttractionId = 2,
                            CityId = 1,
                            Information = "The Kabul Museum was once one of the greatest museums in the world. Its exhibits, ranging from Hellenistic gold coins to Buddhist statuary and Islamic bronzes, testified to Afghanistan’s location at the crossroads of Asia. After years of abuse during the civil war, help from the international community and the peerless dedication of its staff means the museum is slowly rising from the ashes. The museum opened in 1919, and was almost entirely stocked with items excavated in Afghanistan.",
                            IsChildFriendly = true,
                            Location = "Kabul",
                            Name = "Kabul Museum",
                            Rating = 3
                        },
                        new
                        {
                            AttractionId = 3,
                            CityId = 2,
                            Information = "The Sultan of the Seljuq dynasty, Ahmed Sanjar, built the first known shrine at this location. It was destroyed or hidden under earthen embankment during the invasion of Genghis Khan around 1220. In the 15th century, Timurid Sultan Husayn Bayqarah Mirza built the current Blue Mosque here. It is by far the most important landmark in Mazar-i-Sharif and it is believed that the name of city (Noble Shrine, Grave of Hazrat-i-Ali Sharif) originates from this shrine. ",
                            IsChildFriendly = true,
                            Location = "Balkh",
                            Name = "Blue Mosque",
                            Rating = 4
                        },
                        new
                        {
                            AttractionId = 4,
                            CityId = 4,
                            Information = "Kalemegdan is the most popular park among Belgraders and for many tourists visiting Belgrade because of the park's numerous winding walking paths, shaded benches, picturesque fountains, statues, historical architecture and scenic river views (Sahat kula – the clock tower; closed in 2007 for the reconstruction, reopened in April 2014,[6] Zindan kapija – Zindan gate, etc). The former canal which was used for city supplying in the Middle Ages is completely covered by earth but the idea of recreating it resurfaced in the early 2000s. Belgrade Fortress is known for its kilometers-long tunnels, underground corridors and catacombs, which are still largely unexplored. In the true sense, fortress is today the green oasis in the Belgrade's urban area. ",
                            IsChildFriendly = true,
                            Location = "Belgrad",
                            Name = "Kalemegdan Fortress",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 5,
                            CityId = 5,
                            Information = "THE CLOCK TOWER is at the upper town of the fortress. On this site, it used to be an older one which was demolished in 18th century. The radius of the clock is more than two metres long, the four clock faces are directed toward all four cardinal directions, numbers are in roman numerals and the main characteristics of this clock is that the longer hand tells the hours and shorter tells the minutes. This type of a clock needs daily winding up. On the top of the tower there are a vane and a compass. Near the clock tower is, so called, the long barrack i.e. two storey building from the second half of 18th century. At this building, in 1926 was the Aviation NCO school of Kingdom of Serbs, Croats and Slovenians. The bestknown pupil was Franjo Kluz, the aviation pioneer in WWII. One of the most prominent buildings of the upper town is the Leopold’s gate with baroque foreground and suspension bridge, but also with a coat of arms and a motto of the Habsburg monarchy ‘’Viribusunitis’’(by the united forces).",
                            IsChildFriendly = true,
                            Location = "Novi Sad",
                            Name = "Petrovaradin Clock Tower",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 6,
                            CityId = 6,
                            Information = "The Skull Tower was every bit as grim as the name suggests, and was constructed to warn the local Serbs against another rebellion. The tower was built in 1809 using the skulls of 952 fallen Serbian rebels, but less than 100 of the heads remain today.",
                            IsChildFriendly = true,
                            Location = "Niš",
                            Name = "Grimace at the grisly Skull Tower",
                            Rating = 4
                        },
                        new
                        {
                            AttractionId = 7,
                            CityId = 7,
                            Information = "The Tokyo Imperial Palace (Kökyo, literally Imperial Residence) is the primary residence of the Emperor of Japan. It is a large park-like area located in the Chiyoda ward of Tokyo and contains buildings including the main palace (Kyuden), the private residences of the Imperial Family, an archive, museums and administrative offices.It is built on the site of the old Edo Castle.The total area including the gardens is 1.15 square kilometres. During the height of the 1980s Japanese property bubble,the palace grounds were valued by some to be more than the value of all of the real estate in the state of California.",
                            IsChildFriendly = true,
                            Location = "Tokyo",
                            Name = "The Imperial Palace",
                            Rating = 4
                        },
                        new
                        {
                            AttractionId = 8,
                            CityId = 8,
                            Information = "The Hakkeijima Sea Paradise is an amusement park located on a small island just off shore, about 30 minutes by train south of downtown Yokohama. It is one of the most visited amusement parks in Japan and houses quite an impressive aquarium.",
                            IsChildFriendly = true,
                            Location = "Yokohama",
                            Name = "Hakkeijima Sea Paradise",
                            Rating = 3
                        },
                        new
                        {
                            AttractionId = 9,
                            CityId = 9,
                            Information = "Universal Studios Japan (USJ) was the first theme park under the Universal Studios brand to be built in Asia. Opened in March 2001 in the Osaka Bay Area, the theme park occupies an area of 39 hectares and is the most visited amusement park in Japan after Tokyo Disney Resort.",
                            IsChildFriendly = true,
                            Location = "Osaka",
                            Name = "Universal Studios Japan",
                            Rating = 4
                        },
                        new
                        {
                            AttractionId = 10,
                            CityId = 10,
                            Information = "As you drive quietly through Uganda's beautiful countryside, and stop sipping on a white sandy beach and chat with locals, you may forget that the movement in Kampala is just 30 minutes away over Lake Victoria. This bike ride leaves the city behind and covers 12 miles (20 kilometers) of quiet island roads and offers a tour that really gets you off the beaten path.",
                            IsChildFriendly = false,
                            Location = "Kampala",
                            Name = "Lake Victoria Island Biketour",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 11,
                            CityId = 11,
                            Information = "Could not find any Information about Nansana",
                            IsChildFriendly = false,
                            Location = "Nansana",
                            Name = "Nothing at all",
                            Rating = 1
                        },
                        new
                        {
                            AttractionId = 12,
                            CityId = 12,
                            Information = "Indian, Fusion",
                            IsChildFriendly = true,
                            Location = "Kira",
                            Name = "Kati Kati Africa Restaurant",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 13,
                            CityId = 13,
                            Information = "Sail the Caribbean waters of the West Coast of Barbados aboard the El Tigre schooner on this fun half-day cruise, by shuttle. Enjoy free-flow cocktails, including rum, beer and juice, and a light snack as you inhale views of palm trees, the beach and the ocean. Stop for guided snorkeling at a reef known for turtle sighting and a shipwreck that is a lively marine habitat. Upgrade for a longer adventure, with lunch.",
                            IsChildFriendly = true,
                            Location = "Bridgetown",
                            Name = "Barbados Catamaran Snorkling Cruise",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 14,
                            CityId = 14,
                            Information = "Get a comprehensive overview of Barbados on this full-day tour that takes travelers from coast to coast. Listen to comments from a guide on Barbados history and culture as you travel across the island. Since all transport is available, this trip eliminates the problem of renting a car and confuses directions. Highlights include Speightstown, Holetown, North Point, Bathsheba and a buffet lunch at the Sunbury Great House.",
                            IsChildFriendly = true,
                            Location = "Speightstown",
                            Name = "Barbados all day coast to coastal tour",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 15,
                            CityId = 15,
                            Information = "Tour begins in the south coast fishing village of Oistins and cruises east along the coastline with stunning views along the way as well as the historic South Point Lighthouse. Off-road trails lead to the cliffs of the southeast coast which reveal hidden coves, secluded beaches and fantastic picture opportunities in unspoilt coast. On the way back to base, we meet the uniqueness of Chancery Lane Wetlands, a layover for migratory birds arriving in and out of North America, as well as the mysterious Christ Church Parish Church and ending at Oistins Bay for some good old fashioned Bajan room punch to finish this one-of -a-kind scenic experience.",
                            IsChildFriendly = false,
                            Location = "Oistins",
                            Name = "eBike Island Adventures: The Great Adventure Tour",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 16,
                            CityId = 16,
                            Information = "Canada's various wonders are on display at the National Natural History Museum. Such a large country requires a large museum and the Canadian Natural Museum supplies. Explore five floors full of galleries that showcase geology, history and climate in Canada. Hands-on and interactive displays help all ages learn more about Canada and nature.",
                            IsChildFriendly = true,
                            Location = "Ottawa",
                            Name = "Canadian Museum of Nature Entrance",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 17,
                            CityId = 17,
                            Information = "Explore Niagara Falls on a stress-free day trip from Toronto, which also includes wine tasting at a local winery. Explore the cases at your own pace for about three hours of leisure time and upgrade to include a cruise up the Niagara River into the pool in the Canadian Horse Falls for extra close-ups.",
                            IsChildFriendly = true,
                            Location = "Toronto",
                            Name = "Niagara Falls Day Tour from Toronto",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 18,
                            CityId = 18,
                            Information = "Discover Quebec wine country on a small group tasting tour of vineyards and vineyards in the rolling mountains of the Quebec countryside. With half-day and full-day measures, a wine tasting is a great way to experience the Quebec wine while exploring the scenic landscape that is just outside Montreal's city limits and all wine tasting is included.",
                            IsChildFriendly = false,
                            Location = "Montreal",
                            Name = "Small group Quebec wine tour from Montreal",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 19,
                            CityId = 19,
                            Information = "Utforska Brasilias naturliga sida i denna halvdagstur genom att komma genom nationalparken, Brasilias zoo och botaniska trädgården. Omgiven av en utökad flora och fauna kan du komma i kontakt med naturen och förvåna dig över denna otroliga upplevelse.",
                            IsChildFriendly = true,
                            Location = "Brasilia",
                            Name = "Brasilia: Green Brasilia with lunch",
                            Rating = 2
                        },
                        new
                        {
                            AttractionId = 20,
                            CityId = 20,
                            Information = "A visit to the Futebol Museum, inside the Paulo Machado de Carvalho Municipal Stadium in São Paulo, Brazil, shows you how much Brazilians love football (called futebol in Portuguese). Use the English audio guide, watch videos and enjoy interactive screens. Fans and non-fans delve deeper into Brazilian culture by understanding the history and heritage of football in Brazil.",
                            IsChildFriendly = true,
                            Location = "São Paulo",
                            Name = "Football museum",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 21,
                            CityId = 21,
                            Information = "We fly every day with great joy and care, as if it was always the first time, so we enjoy every flight with the same enthusiasm and superior quality in the pictures offered.",
                            IsChildFriendly = false,
                            Location = "Rio de Janeiro",
                            Name = "Hanggliding & Paragliding med Beto Rotor",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 22,
                            CityId = 22,
                            Information = "Visit two of New Zealand's top attractions on a combination trip from Auckland. Explore Shire's hobbies and have a drink at the Green Dragon Inn on a Hobbiton Movie Set tour - a favorite of 'Lord of the Rings' fans - and then listen to Maori legends on a boat ride through the fascinating Waitomo Glowworm Caves. Along the way, walk through some of the most beautiful scenery in the North Island.",
                            IsChildFriendly = true,
                            Location = "Auckland",
                            Name = "Hobbiton Movie Set och Waitomo Glowworm Caves Dagstur från Auckland",
                            Rating = 5
                        },
                        new
                        {
                            AttractionId = 23,
                            CityId = 23,
                            Information = "Pre-order admission to Christchurch Gondola so you can skip the ticket lines for the best views in Christchurch. This stunning attraction, rebuilt since the 2011 earthquake, overlooks the city, Lyttelton Harbor and Canterbury Plains. This tour also offers an upgrade option to include other activities in Christchurch for an extensive experience.",
                            IsChildFriendly = true,
                            Location = "Christchurch",
                            Name = "Christchurch Gondola Ride Ticket",
                            Rating = 4
                        },
                        new
                        {
                            AttractionId = 24,
                            CityId = 24,
                            Information = "Join a wildlife adventure to remember at the Zealandia Wildlife Sanctuary in Wellington. This guided hike is a great way to see some of New Zealand's most extraordinary wildlife, including rare birds such as takahe, cake bush parrots and green geckos. You don't have to worry about the trip being overcrowded - the small group tour has a limit of 10 people for a more personal experience.",
                            IsChildFriendly = true,
                            Location = "Wellington",
                            Name = "Eco Wildlife Tour on Zealandia",
                            Rating = 5
                        });
                });

            modelBuilder.Entity("TravelAPI.Models.CityModel", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CountryId = 1,
                            Name = "Kabul",
                            Population = 4221532
                        },
                        new
                        {
                            CityId = 2,
                            CountryId = 1,
                            Name = "Balkh",
                            Population = 1382200
                        },
                        new
                        {
                            CityId = 3,
                            CountryId = 1,
                            Name = "Kandahar",
                            Population = 614118
                        },
                        new
                        {
                            CityId = 4,
                            CountryId = 2,
                            Name = "Belgrade",
                            Population = 1397939
                        },
                        new
                        {
                            CityId = 5,
                            CountryId = 2,
                            Name = "Novi Sad",
                            Population = 289128
                        },
                        new
                        {
                            CityId = 6,
                            CountryId = 2,
                            Name = "Niš",
                            Population = 185987
                        },
                        new
                        {
                            CityId = 7,
                            CountryId = 3,
                            Name = "Tokyo",
                            Population = 37435191
                        },
                        new
                        {
                            CityId = 8,
                            CountryId = 3,
                            Name = "Yokohama",
                            Population = 3725000
                        },
                        new
                        {
                            CityId = 9,
                            CountryId = 3,
                            Name = "Osaka",
                            Population = 2691000
                        },
                        new
                        {
                            CityId = 10,
                            CountryId = 4,
                            Name = "Kampala",
                            Population = 1680600
                        },
                        new
                        {
                            CityId = 11,
                            CountryId = 4,
                            Name = "Nansana",
                            Population = 365124
                        },
                        new
                        {
                            CityId = 12,
                            CountryId = 4,
                            Name = "Kira",
                            Population = 317157
                        },
                        new
                        {
                            CityId = 13,
                            CountryId = 5,
                            Name = "Bridgetown",
                            Population = 110000
                        },
                        new
                        {
                            CityId = 14,
                            CountryId = 5,
                            Name = "Speightstown",
                            Population = 3634
                        },
                        new
                        {
                            CityId = 15,
                            CountryId = 5,
                            Name = "Oistins",
                            Population = 2285
                        },
                        new
                        {
                            CityId = 16,
                            CountryId = 6,
                            Name = "Ottawa",
                            Population = 994837
                        },
                        new
                        {
                            CityId = 17,
                            CountryId = 6,
                            Name = "Toronto",
                            Population = 2930000
                        },
                        new
                        {
                            CityId = 18,
                            CountryId = 6,
                            Name = "Montreal",
                            Population = 1780000
                        },
                        new
                        {
                            CityId = 19,
                            CountryId = 7,
                            Name = "Brasilia",
                            Population = 4645943
                        },
                        new
                        {
                            CityId = 20,
                            CountryId = 7,
                            Name = "São Paulo",
                            Population = 21846507
                        },
                        new
                        {
                            CityId = 21,
                            CountryId = 7,
                            Name = "Rio de Janeiro",
                            Population = 13458075
                        },
                        new
                        {
                            CityId = 22,
                            CountryId = 8,
                            Name = "Auckland",
                            Population = 1657000
                        },
                        new
                        {
                            CityId = 23,
                            CountryId = 8,
                            Name = "Christchurch",
                            Population = 381500
                        },
                        new
                        {
                            CityId = 24,
                            CountryId = 8,
                            Name = "Wellington",
                            Population = 212700
                        });
                });

            modelBuilder.Entity("TravelAPI.Models.CountryInfoModel", b =>
                {
                    b.Property<int>("CountryInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<int>("BNP")
                        .HasColumnType("int");

                    b.Property<string>("CapitalCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<bool>("RightHandTraffic")
                        .HasColumnType("bit");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryInfoId");

                    b.ToTable("CountryInfo");

                    b.HasData(
                        new
                        {
                            CountryInfoId = 1,
                            Area = 65200,
                            BNP = 19360,
                            CapitalCity = "Kabul",
                            Governance = "Islamic Republic",
                            Language = "Dari/Pashtu/Iranian",
                            NationalDay = "19/08",
                            Population = 50000,
                            RightHandTraffic = true,
                            TimeZone = "GMT+4:30"
                        },
                        new
                        {
                            CountryInfoId = 2,
                            Area = 88361,
                            BNP = 7246,
                            CapitalCity = "Belgrad",
                            Governance = "Parliamentary Republic",
                            Language = "Serbian",
                            NationalDay = "15/02",
                            Population = 80000,
                            RightHandTraffic = true,
                            TimeZone = "GMT+2"
                        },
                        new
                        {
                            CountryInfoId = 3,
                            Area = 377918,
                            BNP = 39289,
                            CapitalCity = "Tokyo",
                            Governance = "Constitutional Monarch",
                            Language = "Japanese/Ryukyuan/Ainu/Orok/Evenki/Nivkh",
                            NationalDay = "11/02",
                            Population = 126244,
                            RightHandTraffic = false,
                            TimeZone = "GMT+9"
                        },
                        new
                        {
                            CountryInfoId = 4,
                            Area = 241037,
                            BNP = 2746,
                            CapitalCity = "Kampala",
                            Governance = "Democratic State",
                            Language = "Bantu/Nilotic/Central Sudanic",
                            NationalDay = "18/05",
                            Population = 4272,
                            RightHandTraffic = false,
                            TimeZone = "GMT+3"
                        },
                        new
                        {
                            CountryInfoId = 5,
                            Area = 431,
                            BNP = 5145,
                            CapitalCity = "Bridgetown",
                            Governance = "Monarch",
                            Language = "English/Bajan Dialect",
                            NationalDay = "30/11",
                            Population = 286641,
                            RightHandTraffic = false,
                            TimeZone = "GMT-4"
                        },
                        new
                        {
                            CountryInfoId = 6,
                            Area = 9985000,
                            BNP = 1713,
                            CapitalCity = "Ottawa",
                            Governance = "Constitutional Monarchy",
                            Language = "French/English",
                            NationalDay = "01/07",
                            Population = 3759,
                            RightHandTraffic = true,
                            TimeZone = "GMT-4"
                        },
                        new
                        {
                            CountryInfoId = 7,
                            Area = 8516000,
                            BNP = 1869,
                            CapitalCity = "Brasília",
                            Governance = "Democratic Federal Republic",
                            Language = "Portuguese",
                            NationalDay = "07/09",
                            Population = 2095,
                            RightHandTraffic = true,
                            TimeZone = "GMT-3"
                        },
                        new
                        {
                            CountryInfoId = 8,
                            Area = 268021,
                            BNP = 2049,
                            CapitalCity = "Wellington",
                            Governance = "Unitary parliamentary constitutional monarchy",
                            Language = "Maori/English",
                            NationalDay = "06/02",
                            Population = 4886,
                            RightHandTraffic = false,
                            TimeZone = "GMT+12"
                        });
                });

            modelBuilder.Entity("TravelAPI.Models.CountryModel", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelRestrictionId")
                        .HasColumnType("int");

                    b.HasKey("CountryId");

                    b.HasIndex("CountryInfoId");

                    b.HasIndex("TravelRestrictionId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryInfoId = 1,
                            Name = "Afghanistan",
                            TravelRestrictionId = 1
                        },
                        new
                        {
                            CountryId = 2,
                            CountryInfoId = 2,
                            Name = "Serbia",
                            TravelRestrictionId = 2
                        },
                        new
                        {
                            CountryId = 3,
                            CountryInfoId = 3,
                            Name = "Japan",
                            TravelRestrictionId = 3
                        },
                        new
                        {
                            CountryId = 4,
                            CountryInfoId = 4,
                            Name = "Uganda",
                            TravelRestrictionId = 4
                        },
                        new
                        {
                            CountryId = 5,
                            CountryInfoId = 5,
                            Name = "Barbados",
                            TravelRestrictionId = 5
                        },
                        new
                        {
                            CountryId = 6,
                            CountryInfoId = 6,
                            Name = "Canada",
                            TravelRestrictionId = 6
                        },
                        new
                        {
                            CountryId = 7,
                            CountryInfoId = 7,
                            Name = "Brazil",
                            TravelRestrictionId = 7
                        },
                        new
                        {
                            CountryId = 8,
                            CountryInfoId = 8,
                            Name = "New Zealand",
                            TravelRestrictionId = 8
                        });
                });

            modelBuilder.Entity("TravelAPI.Models.TravelRestrictionModel", b =>
                {
                    b.Property<int>("TravelRestrictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCitizenshipAllowed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFamilyVisitAllowed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmigrationAllowed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTourismAllowed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisaNeeded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWorkTravelAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.HasKey("TravelRestrictionId");

                    b.ToTable("TravelRestrictions");

                    b.HasData(
                        new
                        {
                            TravelRestrictionId = 1,
                            IsCitizenshipAllowed = true,
                            IsFamilyVisitAllowed = true,
                            IsImmigrationAllowed = true,
                            IsTourismAllowed = false,
                            IsVisaNeeded = true,
                            IsWorkTravelAllowed = true,
                            RiskLevel = 4
                        },
                        new
                        {
                            TravelRestrictionId = 2,
                            IsCitizenshipAllowed = false,
                            IsFamilyVisitAllowed = false,
                            IsImmigrationAllowed = false,
                            IsTourismAllowed = false,
                            IsVisaNeeded = true,
                            IsWorkTravelAllowed = false,
                            RiskLevel = 4
                        },
                        new
                        {
                            TravelRestrictionId = 3,
                            IsCitizenshipAllowed = false,
                            IsFamilyVisitAllowed = false,
                            IsImmigrationAllowed = false,
                            IsTourismAllowed = false,
                            IsVisaNeeded = false,
                            IsWorkTravelAllowed = false,
                            RiskLevel = 3
                        },
                        new
                        {
                            TravelRestrictionId = 4,
                            IsCitizenshipAllowed = false,
                            IsFamilyVisitAllowed = false,
                            IsImmigrationAllowed = true,
                            IsTourismAllowed = false,
                            IsVisaNeeded = true,
                            IsWorkTravelAllowed = false,
                            RiskLevel = 2
                        },
                        new
                        {
                            TravelRestrictionId = 5,
                            IsCitizenshipAllowed = true,
                            IsFamilyVisitAllowed = true,
                            IsImmigrationAllowed = true,
                            IsTourismAllowed = true,
                            IsVisaNeeded = true,
                            IsWorkTravelAllowed = true,
                            RiskLevel = 1
                        },
                        new
                        {
                            TravelRestrictionId = 6,
                            IsCitizenshipAllowed = true,
                            IsFamilyVisitAllowed = true,
                            IsImmigrationAllowed = true,
                            IsTourismAllowed = true,
                            IsVisaNeeded = true,
                            IsWorkTravelAllowed = true,
                            RiskLevel = 3
                        },
                        new
                        {
                            TravelRestrictionId = 7,
                            IsCitizenshipAllowed = true,
                            IsFamilyVisitAllowed = true,
                            IsImmigrationAllowed = true,
                            IsTourismAllowed = true,
                            IsVisaNeeded = true,
                            IsWorkTravelAllowed = true,
                            RiskLevel = 5
                        },
                        new
                        {
                            TravelRestrictionId = 8,
                            IsCitizenshipAllowed = true,
                            IsFamilyVisitAllowed = false,
                            IsImmigrationAllowed = false,
                            IsTourismAllowed = true,
                            IsVisaNeeded = false,
                            IsWorkTravelAllowed = true,
                            RiskLevel = 2
                        });
                });

            modelBuilder.Entity("TravelAPI.Models.AttractionModel", b =>
                {
                    b.HasOne("TravelAPI.Models.CityModel", "City")
                        .WithMany("Attractions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelAPI.Models.CityModel", b =>
                {
                    b.HasOne("TravelAPI.Models.CountryModel", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelAPI.Models.CountryModel", b =>
                {
                    b.HasOne("TravelAPI.Models.CountryInfoModel", "CountryInfo")
                        .WithMany()
                        .HasForeignKey("CountryInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAPI.Models.TravelRestrictionModel", "TravelRestriction")
                        .WithMany()
                        .HasForeignKey("TravelRestrictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
